server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: lost-report-service
    properties:
      schema.registry.url: http://localhost:8081
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth/.well-known/jwks.json
  data:
    mongodb:
      host: localhost
      port: 27017
      username: lrs
      password: lrs
      database: lrs-db
  auth0:
    client-id: gGcs9fp7dmJfPz94lbtYLKeY3FFxWbtD
    client-secret: CAEG0vfzJs8Kg3oIAgGZxLtwmpeS9bCsWjTf5USyLR-8JfmjBGzlyoY3mHfqanT7
    audience: https://lost-n-found.eu.auth0.com/api/v2/
    grant_type: client_credentials
springdoc:
  swagger-ui:
    disable-swagger-default-url: true