spring:
  kafka:
    bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
    client-id: lost-report-service
    properties:
      schema.registry.url: http://schema-registry-svc.kafka:9099
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${SCHEMA_REGISTRY_USERNAME}:${SCHEMA_REGISTRY_PASSWORD}
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://lost-n-found.eu.auth0.com/.well-known/jwks.json
  data:
    mongodb:
      host: mongodb-svc.mongo
      port: 27017
      username: lrs
      password: lrs
      database: lrs-db